name: calculator_lite
description: 'Calculator Lite: Make faster calculations, display latest
  currencies, endless history scrolling :D'

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  angles: ^2.1.0
  animations: ^2.0.0
  archive: ^2.0.13
  auto_size_text_field: ^0.1.6
  country_icons: ^2.0.2
  decimal: ^1.0.0+1
  device_info: ^2.0.0
  dio: ^4.0.0
  excel: ^1.1.5
  flutter_animator: ^3.1.1
  flutter_slidable: ^0.6.0
  flutter_statusbarcolor: ^0.2.3
  flutter_windowmanager: ^0.0.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  in_app_purchase: ^0.5.2
  intl: ^0.17.0
  math_expressions: ^2.0.1
  octo_image: ^1.0.0+1
  path_provider: ^1.6.24
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^0.5.10
  slide_popup_dialog: ^0.0.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  flutter_launcher_icons: ^0.8.0
  flutter_rename_app: ^1.0.0
  hive_generator: ^0.8.2

flutter_rename_app:
  application_name: Calculator Lite

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
