name: calculator_lite
description: 'Calculator Lite: Make faster calculations, display latest
  currencies, previous history scrolling and so much more!'

publish_to: 'none'
version: 2.0.0+20

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  angles: ^2.1.1
  animations: ^2.0.11
  archive: ^3.6.1
  auto_size_text_field: ^2.2.4
  country_icons: ^3.0.0
  decimal: ^3.2.1
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  excel: ^4.0.6
  flutter_animator: ^3.2.2
  flutter_slidable: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.2.1
  intl: ^0.20.2
  math_expressions: ^2.7.0
  octo_image: ^2.1.0
  path_provider: ^2.1.5
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10
  quick_actions: ^1.1.0
  flutter_displaymode: ^0.6.0
  share_plus: ^11.0.0
  slide_popup_dialog_null_safety: ^1.0.0
  flutter_statusbarcolor_ns: ^0.6.0
  animated_search_bar: ^2.8.0
  nil: ^1.1.1
  auto_size_text: ^3.0.0
  charcode: ^1.4.0
  flutter_windowmanager_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_generator: ^2.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
