name: calculator_lite
description: 'Calculator Lite: Make faster calculations, display latest
  currencies, previous history scrolling and so much more!'

publish_to: 'none'
version: 1.0.6+16

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  angles: ^2.1.1
  animations: ^2.0.7
  archive: ^3.3.7
  auto_size_text_field: ^2.2.1
  country_icons: ^2.0.2
  decimal: ^2.3.2
  device_info_plus: ^9.0.2
  dio: ^5.1.1
  excel: ^2.0.1
  flutter_animator: ^3.2.2
  flutter_slidable: ^3.0.0
  flutter_windowmanager: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.1.5
  intl: ^0.18.1
  math_expressions: ^2.4.0
  octo_image: ^1.0.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  in_app_review: ^2.0.6
  quick_actions: ^1.0.2
  flutter_displaymode: ^0.6.0
  share_plus: ^7.0.2
  slide_popup_dialog_null_safety: ^1.0.0
  flutter_statusbarcolor_ns: ^0.5.0
  animated_search_bar: ^2.5.0
  nil: ^1.1.1
  auto_size_text: ^3.0.0
  charcode: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.1
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
